spring.application.name=taskflow

# CONFIGURATION DE LA BASE MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow
spring.datasource.username=root
spring.datasource.password=

# Driver JDBC utilisé pour communiquer avec MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURATION JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# Affiche les requêtes SQL générées par Hibernate dans la console
spring.jpa.show-sql=true
# Formate les requêtes SQL pour les rendre plus lisibles
spring.jpa.properties.hibernate.format_sql=true
# Permet à Hibernate de générer du SQL compatible avec MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JWT CONFIGURATION
#clé secrète en Base64 (obligatoire pour JWT)
jwt.secret=VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLXRhc2tmbG93LWFwcA==
#15 minutes (Access Token)
jwt.access-expiration=900000
#7 jours (Refresh Token)
jwt.refresh-expiration=604800000

# CONFIGURATION DU SERVEUR
server.port=8080